import React,{useState}from'react';
import axios from'axios';
import{Sparkles,FileText,Briefcase,RefreshCw,Copy,Check,ChevronDown}from'lucide-react';
import OutreachSender from'./OutreachSender';
const API=import.meta.env.VITE_API_URL||'http://localhost:4000/api';
const api=axios.create({baseURL:API});
const box={border:'1px solid rgba(255,255,255,.09)',borderRadius:14,padding:14,marginTop:12,background:'rgba(255,255,255,.025)'};
const btn={border:'1px solid rgba(255,255,255,.12)',borderRadius:9,padding:'8px 11px',background:'transparent',color:'inherit',cursor:'pointer',display:'inline-flex',alignItems:'center',gap:7,fontSize:12};
export default function LeadActions({lead}){
 const[data,setData]=useState(null),[kind,setKind]=useState(''),[loading,setLoading]=useState(false),[copied,setCopied]=useState('');
 const run=async type=>{setLoading(true);setKind(type);try{const path=type==='report'?`/leads/${encodeURIComponent(lead.id)}/report`:`/leads/${encodeURIComponent(lead.id)}/proposal`;const r=await api.get(path);setData(r.data)}catch(e){setData({error:e.response?.data?.error||'Could not generate this asset.'})}finally{setLoading(false)}};
 const copy=async(text,key)=>{try{await navigator.clipboard.writeText(text);setCopied(key);setTimeout(()=>setCopied(''),1600)}catch{}};
 const insight=lead=>{const gaps=[];if(!lead.website)gaps.push('No dedicated website');else{if(lead.https===false)gaps.push('HTTPS not detected');if(lead.mobileFriendlySignal===false)gaps.push('Mobile viewport not detected');if(Number(lead.seoScore||0)<60)gaps.push(`SEO signals at ${Number(lead.seoScore||0)}%`);if(lead.hasContactLink===false)gaps.push('No obvious contact or booking path')}if(!(lead.contactEmail||lead.email))gaps.push('No public email');if(!(lead.contactPhone||lead.phone))gaps.push('No public phone');const priority=Math.min(100,Math.max(0,Number(lead.priorityScore||lead.score||0)+(lead.website?0:12)));const service=lead.recommendedService||({restaurant:'Website + online ordering + local SEO',cafe:'Website + online ordering + local SEO',gym:'Website + lead capture + membership enquiry',fitness:'Website + lead capture + membership enquiry',dentist:'Website + appointment booking + local SEO',doctor:'Website + appointment booking + local SEO',clinic:'Website + appointment booking + local SEO',salon:'Website + appointment booking + WhatsApp enquiry',hotel:'Website + direct booking + enquiry funnel'}[String(lead.category||'').toLowerCase()]||'Modern business website + lead capture');return{priority,gaps:gaps.slice(0,6),service,urgency:priority>=85?'Immediate review':priority>=70?'High attention':priority>=40?'Worth nurturing':'Low attention'}};
 const i=insight(lead);
 const proposalText=data?.projectObjective?`${data.projectObjective}\n\nDeliverables:\n${(data.deliverables||[]).map(x=>'- '+x).join('\n')}\n\nProcess:\n${(data.process||[]).map(x=>'- '+x).join('\n')}`:'';
 return <div style={{...box,marginTop:16}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10}}><div><h3 style={{margin:'0 0 5px',display:'flex',alignItems:'center',gap:7}}><Sparkles size={15}/>Lead intelligence</h3><small style={{opacity:.65}}>Priority {i.priority}/100 · {i.urgency}</small></div><button style={btn}onClick={()=>{setData(null);setKind('')}}><ChevronDown size={14}/></button></div><div style={{marginTop:12,fontSize:12}}><b>Recommended service</b><p style={{margin:'5px 0 10px',opacity:.8}}>{i.service}</p><b>Key gaps</b>{i.gaps.length?<ul style={{margin:'5px 0 0',paddingLeft:18}}>{i.gaps.map(x=><li key={x}>{x}</li>)}</ul>:<p style={{opacity:.7}}>No major gaps detected.</p>}</div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}><button style={btn}onClick={()=>run('report')}disabled={loading}><FileText size={14}/>{loading&&kind==='report'?<RefreshCw className="spin" size={14}/>:null} Generate report</button><button style={btn}onClick={()=>run('proposal')}disabled={loading}><Briefcase size={14}/>{loading&&kind==='proposal'?<RefreshCw className="spin" size={14}/>:null} Generate proposal</button></div>{data?.error&&<p style={{color:'var(--danger,#ff6b6b)',fontSize:12}}>{data.error}</p>}{data&&!data.error&&kind==='report'&&<div style={box}><b>{data.title}</b><p style={{fontSize:12,opacity:.75}}>{data.summary?.category} · {data.summary?.location}</p><div style={{fontSize:12}}><b>Opportunity</b><p>Score {data.summary?.opportunityScore}/100 · Priority {data.summary?.priorityScore}/100</p><b>Audit findings</b><ul>{(data.websiteAudit?.issues||[]).map(x=><li key={x}>{x}</li>)}</ul><b>Outreach</b><p style={{whiteSpace:'pre-wrap'}}>{data.outreach?.message||data.outreach?.status}</p></div><button style={btn}onClick={()=>copy(JSON.stringify(data,null,2),'report')}>{copied==='report'?<Check size={14}/>:<Copy size={14}/>} Copy report JSON</button></div>}{data&&!data.error&&kind==='proposal'&&<div style={box}><b>{data.title||`Proposal — ${lead.name}`}</b><p style={{fontSize:12,whiteSpace:'pre-wrap'}}>{data.projectObjective||''}</p><b>Deliverables</b><ul>{(data.deliverables||[]).map(x=><li key={x}>{x}</li>)}</ul><b>Process</b><ul>{(data.process||[]).map(x=><li key={x}>{x}</li>)}</ul>{data.nextStep&&<p><b>Next step:</b> {data.nextStep}</p>}{proposalText&&<button style={btn}onClick={()=>copy(proposalText,'proposal')}>{copied==='proposal'?<Check size={14}/>:<Copy size={14}/>} Copy proposal</button>}</div>}<OutreachSender lead={lead}/></div>;
}
