import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import axios from 'axios';
import {Search, Download, Globe, Phone, Mail, MapPin, X, Bookmark, Trash2, ExternalLink, Radar, Sparkles, RefreshCw, CheckCircle2, AlertTriangle, ChevronRight, Target, ShieldCheck} from 'lucide-react';
import './styles.css';

const API=import.meta.env.VITE_API_URL || 'http://localhost:4000/api';
const api=axios.create({baseURL:API});

function App(){
 const [form,setForm]=useState({location:'Dombivli',category:'',limit:10});
 const [leads,setLeads]=useState([]); const [saved,setSaved]=useState([]); const [selected,setSelected]=useState(null);
 const [loading,setLoading]=useState(false); const [savedLoading,setSavedLoading]=useState(true); const [searched,setSearched]=useState(false); const [error,setError]=useState(''); const [provider,setProvider]=useState('demo');
 const [view,setView]=useState('discover');

 const loadSaved=()=>{setSavedLoading(true);api.get('/leads').then(r=>setSaved(r.data||[])).catch(()=>{}).finally(()=>setSavedLoading(false));};
 useEffect(()=>{loadSaved();},[]);
 const search=async e=>{e?.preventDefault();setLoading(true);setError('');try{const r=await api.post('/search',{...form,limit:Number(form.limit)});setLeads(r.data.leads||[]);setProvider(r.data.meta?.source||'demo');setSearched(true);setView('discover');}catch(err){setError(err.response?.data?.error||'Could not reach the API. Start the server and try again.');}finally{setLoading(false);}};
 const save=async lead=>{try{const r=await api.post('/leads',lead);setSaved(s=>[...s.filter(x=>x.id!==lead.id),r.data]);setLeads(ls=>ls.map(x=>x.id===lead.id?{...x,saved:true}:x));setSelected(x=>x?.id===lead.id?{...x,saved:true}:x);}catch{setError('Could not save lead.');}};
 const remove=async id=>{try{await api.delete('/leads/'+encodeURIComponent(id));setSaved(s=>s.filter(x=>x.id!==id));setLeads(ls=>ls.map(x=>x.id===id?{...x,saved:false}:x));if(selected?.id===id)setSelected(x=>x?{...x,saved:false}:x);}catch{setError('Could not remove lead.');}};
 const visibleLeads=view==='saved'?saved:leads;
 const high=visibleLeads.filter(x=>Number(x.score)>=70).length;
 const noWebsite=visibleLeads.filter(x=>!x.website).length;
 const audited=visibleLeads.filter(x=>x.website).length;
 const avg=visibleLeads.length?Math.round(visibleLeads.reduce((a,x)=>a+Number(x.score||0),0)/visibleLeads.length):0;
 const exportUrl=API+'/export.csv';
 return <div className="app">
  <header><div className="brand"><div className="logo"><Radar size={21}/></div><div><b>LeadHunter<span> AI</span></b><small>CLIENT PROSPECTING WORKSPACE</small></div></div><nav><button className={view==='discover'?'active':''} onClick={()=>setView('discover')}>Discover</button><button className={view==='saved'?'active':''} onClick={()=>setView('saved')}>Saved <i>{saved.length}</i></button></nav><div className="header-actions"><a className="icon-link" href="https://github.com/esakki-2008/LeadHunter" target="_blank" rel="noreferrer" title="Open GitHub"><ExternalLink size={16}/></a></div></header>
  <main>
   {view==='discover'?<>
    <section className="hero"><div><div className="eyebrow"><Sparkles size={14}/> FIND BETTER PROSPECTS</div><h1>Turn local businesses<br/><em>into opportunities.</em></h1><p>Discover businesses, audit their web presence, and prioritize who needs your services most.</p></div><div className="flow"><span>SEARCH</span><b>→</b><span>AUDIT</span><b>→</b><span>SCORE</span><b>→</b><span>OUTREACH</span></div></section>
    <form className="searchbox" onSubmit={search}><label>LOCATION<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})} placeholder="e.g. Dombivli"/></label><label>CATEGORY<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="e.g. restaurants, gyms"/></label><label>LEADS<select value={form.limit} onChange={e=>setForm({...form,limit:e.target.value})}>{[5,10,20,30,50].map(n=><option key={n} value={n}>{n}</option>)}</select></label><button className="primary" disabled={loading}>{loading?<RefreshCw className="spin" size={18}/>:<Search size={18}/>} {loading?'Hunting…':'Find leads'}</button></form>
    {error&&<div className="error"><AlertTriangle size={16}/>{error}</div>}
    {searched&&<div className="provider"><span><span className="live-dot"/> Search source: <b>{provider}</b></span><span>{leads.length} businesses returned</span></div>}
    <section className="stats"><Stat n={leads.length} label="Businesses found" icon={<Target size={17}/>}/><Stat n={high} label="High opportunity" icon={<Sparkles size={17}/>}/><Stat n={noWebsite} label="No website" icon={<Globe size={17}/>}/><Stat n={audited} label="Websites audited" icon={<ShieldCheck size={17}/>}/><Stat n={avg} label="Average score" icon={<Radar size={17}/>}/></section>
    <Results leads={leads} searched={searched} loading={loading} onSave={save} onOpen={setSelected}/>
   </>:<SavedView saved={saved} loading={savedLoading} onOpen={setSelected} onRemove={remove}/>} 
  </main>
  {(view==='discover'&&saved.length>0)&&<div className="bottom-bar"><div><b>{saved.length} saved lead{saved.length===1?'':'s'}</b><span>Ready for outreach</span></div><a className="export" href={exportUrl}><Download size={15}/> Export CSV</a></div>}
  {selected&&<Drawer lead={selected} onClose={()=>setSelected(null)} onSave={save} onRemove={remove} saved={saved.some(x=>x.id===selected.id)}/>}<footer>LeadHunter AI · Prospecting workspace · Use public business information responsibly</footer>
 </div>;
}
function Stat({n,label,icon}){return <div className="stat"><div className="stat-icon">{icon}</div><div><b>{n}</b><span>{label}</span></div></div>}
function Results({leads,searched,loading,onSave,onOpen}){if(loading)return <div className="loading-grid">{[1,2,3,4,5,6].map(i=><div className="skeleton" key={i}><div/><div/><div/><div/></div>)}</div>;return <><div className="section-head"><div><div className="eyebrow">PROSPECTS</div><h2>{searched?'Search results':'Ready to hunt'}</h2><p>{searched?`${leads.length} businesses analyzed and scored.`:'Choose a location and category to find potential clients.'}</p></div>{leads.length>0&&<span className="result-count">{leads.length} results</span>}</div><div className="grid">{leads.map(l=><LeadCard key={l.id} lead={l} onSave={onSave} onOpen={onOpen}/>)}{searched&&!leads.length&&<div className="empty"><Target size={28}/><b>No businesses found</b><span>Try a broader location or category.</span></div>}{!searched&&!leads.length&&<div className="empty intro"><Radar size={30}/><b>Your next client is hiding in plain sight.</b><span>Start with a local area and a business category.</span></div>}</div></>}
function LeadCard({lead,onSave,onOpen}){const score=Number(lead.score||0);const opportunity=lead.scoreLabel||'Opportunity';return <article className="card"><div className="card-top"><div className="avatar">{lead.name?.slice(0,1)?.toUpperCase()}</div><div className="card-title"><b title={lead.name}>{lead.name}</b><span>{lead.category||'Business'}</span></div><Score score={score} label={opportunity}/></div><div className="meta"><span><MapPin size={14}/>{lead.location||'Location unavailable'}</span><span className={lead.website?'ok':'warn'}>{lead.website?<><Globe size={14}/> {lead.websiteStatus||'Website'}</>:<><AlertTriangle size={14}/> No website</>}</span></div><div className="audit-strip"><Audit label="SEO" value={lead.website?`${lead.seoScore??0}%`:'—'} tone={Number(lead.seoScore)<60&&lead.website?'warn':''}/><Audit label="HTTPS" value={lead.website?(lead.https?'Yes':'No'):'—'} tone={lead.website&&!lead.https?'warn':'ok'}/><Audit label="Mobile" value={lead.website?(lead.mobileFriendlySignal?'Yes':'No'):'—'} tone={lead.website&&!lead.mobileFriendlySignal?'warn':'ok'}/></div><div className="signals">{[...(lead.reasons||[]),...(lead.websiteOpportunityReasons||[])].filter((v,i,a)=>a.indexOf(v)===i).slice(0,3).map(r=><span key={r}>{r}</span>)}</div><div className="card-actions"><button onClick={()=>onOpen(lead)}>View audit <ChevronRight size={14}/></button><button className="save" onClick={()=>onSave(lead)} disabled={lead.saved}><Bookmark size={15}/>{lead.saved?'Saved':'Save lead'}</button></div></article>}
function Audit({label,value,tone}){return <div><span>{label}</span><b className={tone}>{value}</b></div>}
function Score({score,label}){return <div className="score"><div><b>{score}</b><small>/100</small></div><span>{label.replace(' opportunity','')}</span></div>}
function SavedView({saved,loading,onOpen,onRemove}){return <><section className="saved-hero"><div><div className="eyebrow"><Bookmark size={14}/> YOUR PIPELINE</div><h1>Saved <em>leads.</em></h1><p>Your shortlist of businesses to research and contact.</p></div><a className="export" href={API+'/export.csv'}><Download size={15}/> Export CSV</a></section><div className="section-head"><div><h2>Lead pipeline</h2><p>{saved.length} saved business{saved.length===1?'':'es'}</p></div></div>{loading?<div className="empty">Loading saved leads…</div>:saved.length?<div className="saved-list">{saved.map(l=><div className="saved-row" key={l.id}><div className="saved-main"><div className="avatar">{l.name?.slice(0,1)?.toUpperCase()}</div><div><b>{l.name}</b><span>{l.category||'Business'} · {l.location||'Unknown location'}</span></div></div><Score score={Number(l.score||0)} label={l.scoreLabel||'Opportunity'}/><button onClick={()=>onOpen(l)}>View audit <ChevronRight size={14}/></button><button className="danger" onClick={()=>onRemove(l.id)}><Trash2 size={15}/></button></div>)}</div>:<div className="empty"><Bookmark size={28}/><b>No saved leads yet</b><span>Save promising businesses from Discover to build your pipeline.</span></div>}</>}
function Drawer({lead,onClose,onSave,onRemove,saved}){const reasons=[...(lead.reasons||[]),...(lead.websiteOpportunityReasons||[])].filter((v,i,a)=>a.indexOf(v)===i);return <div className="overlay" onClick={onClose}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose}><X size={18}/></button><div className="drawer-head"><div className="drawer-avatar">{lead.name?.slice(0,1)?.toUpperCase()}</div><div><div className="eyebrow">LEAD PROFILE</div><h2>{lead.name}</h2><p>{lead.category||'Business'} · {lead.location||'Unknown location'}</p></div></div><div className="bigscore"><div><b>{lead.score??0}</b><span>/100</span></div><strong>{lead.scoreLabel||'Opportunity'}</strong><small>Based on the available business and website signals.</small></div><h3>Website audit</h3><div className="audit"><Audit label="Status" value={lead.website?lead.websiteStatus:'Missing'} tone={lead.website?'ok':'warn'}/><Audit label="HTTPS" value={lead.website?(lead.https?'Yes':'No'):'—'} tone={lead.website&&!lead.https?'warn':'ok'}/><Audit label="Response" value={lead.pageLoadMs?`${lead.pageLoadMs} ms`:'—'}/><Audit label="Mobile" value={lead.website?(lead.mobileFriendlySignal?'Detected':'Not detected'):'—'} tone={lead.website&&!lead.mobileFriendlySignal?'warn':'ok'}/><Audit label="SEO score" value={lead.website?`${lead.seoScore??0}%`:'—'} tone={lead.website&&Number(lead.seoScore)<60?'warn':'ok'}/><Audit label="Images / alt" value={lead.website?`${lead.imageCount??0} / ${lead.imagesMissingAlt??0}`:'—'}/></div><h3>Contact signals</h3><div className="contact">{lead.phone&&<span><Phone size={15}/>{lead.phone}</span>}{lead.email&&<span><Mail size={15}/>{lead.email}</span>}{lead.website&&<a href={lead.website} target="_blank" rel="noreferrer"><Globe size={15}/>Open website <ExternalLink size={13}/></a>}{!lead.phone&&!lead.email&&!lead.website&&<span className="muted">No public contact signal returned.</span>}</div><h3>Why this is an opportunity</h3><ul>{reasons.length?reasons.map(r=><li key={r}><CheckCircle2 size={14}/>{r}</li>):<li><CheckCircle2 size={14}/>No major opportunity signals detected.</li>}</ul><div className="drawer-actions">{saved?<button className="secondary" onClick={()=>onRemove(lead.id)}><Trash2 size={15}/> Remove saved</button>:<button className="primary full" onClick={()=>onSave(lead)}><Bookmark size={15}/> Save lead</button>}</div></aside></div>}

createRoot(document.getElementById('root')).render(<App/>);
