import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import axios from 'axios';
import {Search, Download, Globe, Phone, Mail, MapPin, X, Bookmark, Trash2, ExternalLink, Radar, Sparkles} from 'lucide-react';
import {BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer} from 'recharts';
import './styles.css';

const API=import.meta.env.VITE_API_URL || 'http://localhost:4000/api';
const api=axios.create({baseURL:API});

function App(){
 const [form,setForm]=useState({location:'Dombivli',category:'',limit:10});
 const [leads,setLeads]=useState([]); const [saved,setSaved]=useState([]); const [selected,setSelected]=useState(null); const [loading,setLoading]=useState(false); const [searched,setSearched]=useState(false); const [error,setError]=useState('');
 const search=async e=>{e?.preventDefault();setLoading(true);setError('');try{const r=await api.post('/search',form);setLeads(r.data.leads);setSearched(true)}catch(err){setError(err.response?.data?.error||'Could not reach the API. Start the server and try again.')}finally{setLoading(false)}};
 useEffect(()=>{api.get('/leads').then(r=>setSaved(r.data)).catch(()=>{})},[]);
 const save=async lead=>{try{const r=await api.post('/leads',lead);setSaved(s=>[...s.filter(x=>x.id!==lead.id),r.data]);setLeads(ls=>ls.map(x=>x.id===lead.id?{...x,saved:true}:x))}catch{setError('Could not save lead')}};
 const remove=async id=>{await api.delete('/leads/'+id);setSaved(s=>s.filter(x=>x.id!==id));setLeads(ls=>ls.map(x=>x.id===id?{...x,saved:false}:x))};
 const chart=useMemo(()=>[70,40,10].map((min,i)=>({name:['High','Medium','Low'][i],count:leads.filter(x=>x.score>=(i===0?70:i===1?40:0)&&x.score<(i===2?40: i===1?70:101)).length})),[leads]);
 return <div className="app"><header><div className="brand"><div className="logo"><Radar size={21}/></div><div><b>LeadHunter<span> AI</span></b><small>CLIENT PROSPECTING WORKSPACE</small></div></div><div className="header-actions"><button className="ghost" onClick={()=>document.getElementById('saved').scrollIntoView({behavior:'smooth'})}><Bookmark size={16}/> Saved <i>{saved.length}</i></button><a className="icon-link" href="https://github.com/esakki-2008/LeadHunter" target="_blank"><ExternalLink size={16}/></a></div></header>
 <main><section className="hero"><div><div className="eyebrow"><Sparkles size={14}/> FIND BETTER PROSPECTS</div><h1>Turn local businesses<br/><em>into opportunities.</em></h1><p>Discover businesses, audit their web presence, and prioritize who needs your services most.</p></div><div className="flow"><span>SEARCH</span><b>→</b><span>ANALYZE</span><b>→</b><span>SCORE</span></div></section>
 <form className="searchbox" onSubmit={search}><label>LOCATION<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})} placeholder="e.g. Dombivli"/></label><label>CATEGORY<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="e.g. restaurants, gyms"/></label><label>LEADS<select value={form.limit} onChange={e=>setForm({...form,limit:e.target.value})}>{[5,10,20,30,50].map(n=><option key={n}>{n}</option>)}</select></label><button className="primary" disabled={loading}><Search size={18}/>{loading?'Searching…':'Find leads'}</button></form>
 {error&&<div className="error">{error}</div>}
 <section className="stats"><Stat n={leads.length} label="Found"/><Stat n={leads.filter(x=>x.score>=70).length} label="High opportunity"/><Stat n={leads.filter(x=>!x.website).length} label="No website"/><div className="chart"><ResponsiveContainer width="100%" height={65}><BarChart data={chart}><XAxis dataKey="name" hide/><YAxis hide/><Tooltip/><Bar dataKey="count" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></section>
 <div className="section-head"><div><h2>{searched?'Search results':'Ready to hunt'}</h2><p>{searched?`${leads.length} businesses analyzed`:'Run a search to find your next client.'}</p></div>{saved.length>0&&<a className="export" href={API+'/export.csv'}><Download size={15}/> Export CSV</a>}</div>
 <div className="grid">{leads.map(l=><LeadCard key={l.id} lead={l} onSave={save} onOpen={setSelected}/>)}{searched&&!leads.length&&<div className="empty">No matches in the current demo dataset. Try another category or location.</div>}</div>
 <section id="saved" className="saved"><div className="section-head"><div><h2>Saved leads</h2><p>Your shortlist for outreach.</p></div></div>{saved.length?<div className="saved-list">{saved.map(l=><div className="saved-row" key={l.id}><div><b>{l.name}</b><span>{l.category} · {l.location}</span></div><strong>{l.score}</strong><button onClick={()=>setSelected(l)}>View</button><button className="danger" onClick={()=>remove(l.id)}><Trash2 size={15}/></button></div>)}</div>:<div className="empty">No saved leads yet.</div>}</section>
 </main>{selected&&<Drawer lead={selected} onClose={()=>setSelected(null)} onSave={save} saved={saved.some(x=>x.id===selected.id)}/>}<footer>LeadHunter AI · MVP · Built for ethical, legitimate business prospecting</footer></div>
}
function Stat({n,label}){return <div className="stat"><b>{n}</b><span>{label}</span></div>}
function LeadCard({lead,onSave,onOpen}){return <article className="card"><div className="card-top"><div className="avatar">{lead.name?.slice(0,1)}</div><div className="card-title"><b>{lead.name}</b><span>{lead.category}</span></div><div className="score"><b>{lead.score}</b><small>{lead.scoreLabel.replace(' opportunity','')}</small></div></div><div className="meta"><span><MapPin size={14}/>{lead.location}</span><span className={lead.website?'ok':'warn'}><Globe size={14}/>{lead.website?lead.websiteStatus:'No website'}</span></div><div className="signals">{lead.reasons?.slice(0,2).map(r=><span key={r}>{r}</span>)}</div><div className="card-actions"><button onClick={()=>onOpen(lead)}>Details</button><button className="save" onClick={()=>onSave(lead)} disabled={lead.saved}><Bookmark size={15}/>{lead.saved?'Saved':'Save lead'}</button></div></article>}
function Drawer({lead,onClose,onSave,saved}){return <div className="overlay" onClick={onClose}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose}><X/></button><div className="drawer-avatar">{lead.name?.slice(0,1)}</div><div className="eyebrow">LEAD PROFILE</div><h2>{lead.name}</h2><p>{lead.category} · {lead.location}</p><div className="bigscore"><b>{lead.score}</b><span>{lead.scoreLabel}</span></div><h3>Website audit</h3><div className="audit"><div><span>Status</span><b>{lead.website?lead.websiteStatus:'Missing'}</b></div><div><span>HTTPS</span><b>{lead.https?'Yes':'No'}</b></div><div><span>Response</span><b>{lead.pageLoadMs?`${lead.pageLoadMs} ms`:'—'}</b></div><div><span>Mobile signal</span><b>{lead.mobileFriendlySignal?'Detected':'Not detected'}</b></div></div><h3>Contact</h3><div className="contact">{lead.phone&&<span><Phone size={15}/>{lead.phone}</span>}{lead.email&&<span><Mail size={15}/>{lead.email}</span>}{lead.website&&<a href={lead.website} target="_blank"><Globe size={15}/>{lead.website}</a>}</div><h3>Why this score?</h3><ul>{lead.reasons?.map(r=><li key={r}>{r}</li>)}</ul>{!saved&&<button className="primary full" onClick={()=>onSave(lead)}>Save lead</button>}</aside></div>}

createRoot(document.getElementById('root')).render(<App/>);
