import React,{useEffect,useState}from'react';
import axios from'axios';
import{Mail,MessageCircle,Send,RefreshCw,Check,AlertTriangle}from'lucide-react';
const API=import.meta.env.VITE_API_URL||'http://localhost:4000/api';
const api=axios.create({baseURL:API});
export default function OutreachSender({lead,onUpdate}){
 const[channel,setChannel]=useState(lead.contactEmail||lead.email?'email':'whatsapp');
 const[message,setMessage]=useState(lead.outreachMessage||'');const[subject,setSubject]=useState(`Quick idea for ${lead.name}`);const[status,setStatus]=useState('');const[error,setError]=useState('');const[sending,setSending]=useState(false);
 useEffect(()=>{setMessage(lead.outreachMessage||'');setChannel(lead.contactEmail||lead.email?'email':'whatsapp');setStatus('');setError('')},[lead.id]);
 const recipient=channel==='email'?(lead.contactEmail||lead.email):(lead.contactPhone||lead.phone);
 const send=async()=>{setSending(true);setStatus('');setError('');try{const r=await api.post('/outreach/send',{lead,channel,subject,message});setStatus(`Sent via ${channel==='email'?'email':'WhatsApp'}`);onUpdate?.({...lead,...r.data.lead});}catch(e){setError(e.response?.data?.error||'Message could not be sent.');}finally{setSending(false)}};
 return <div style={{border:'1px solid rgba(255,255,255,.09)',borderRadius:14,padding:14,marginTop:16,background:'rgba(255,255,255,.025)'}}><h3 style={{margin:'0 0 10px',display:'flex',alignItems:'center',gap:7}}><Send size={15}/> Send outreach</h3><div style={{display:'flex',gap:8,marginBottom:10}}><button type="button" onClick={()=>setChannel('email')} style={{border:'1px solid rgba(255,255,255,.12)',borderRadius:9,padding:'8px 11px',background:channel==='email'?'rgba(255,255,255,.1)':'transparent',color:'inherit',cursor:'pointer',display:'inline-flex',alignItems:'center',gap:6,fontSize:12}}><Mail size={14}/> Email</button><button type="button" onClick={()=>setChannel('whatsapp')} style={{border:'1px solid rgba(255,255,255,.12)',borderRadius:9,padding:'8px 11px',background:channel==='whatsapp'?'rgba(255,255,255,.1)':'transparent',color:'inherit',cursor:'pointer',display:'inline-flex',alignItems:'center',gap:6,fontSize:12}}><MessageCircle size={14}/> WhatsApp</button></div>{channel==='email'&&<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Email subject" style={{width:'100%',boxSizing:'border-box',marginBottom:8,padding:9,borderRadius:8,border:'1px solid rgba(255,255,255,.12)',background:'transparent',color:'inherit'}}/>}<textarea value={message} onChange={e=>setMessage(e.target.value)} rows={6} placeholder="Write a personalized message…" style={{width:'100%',boxSizing:'border-box',padding:9,borderRadius:8,border:'1px solid rgba(255,255,255,.12)',background:'transparent',color:'inherit',resize:'vertical'}}/><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:8,marginTop:9}}><small style={{opacity:.65}}>{recipient?`Recipient: ${recipient}`:'No public recipient found'}</small><button type="button" onClick={send} disabled={sending||!recipient||!message.trim()} style={{border:0,borderRadius:9,padding:'9px 13px',background:'var(--accent,#fff)',color:'var(--bg,#111)',cursor:sending||!recipient||!message.trim()?'not-allowed':'pointer',display:'inline-flex',alignItems:'center',gap:7,fontSize:12,fontWeight:700}}>{sending?<RefreshCw className="spin" size={14}/>:<Send size={14}/>} {sending?'Sending…':'Send now'}</button></div>{status&&<div style={{marginTop:9,fontSize:12,display:'flex',alignItems:'center',gap:6}}><Check size={14}/> {status}</div>}{error&&<div style={{marginTop:9,fontSize:12,display:'flex',alignItems:'center',gap:6,color:'var(--danger,#ff6b6b)'}}><AlertTriangle size={14}/> {error}</div>}</div>;
}
