function clean(value=''){return String(value||'').trim()}

const SERVICE_BY_CATEGORY={
 restaurant:'Website redesign + online ordering',cafe:'Website redesign + online ordering',bakery:'Website + online ordering',
 gym:'Website + lead capture',fitness:'Website + lead capture',dentist:'Website + appointment booking',doctor:'Website + appointment booking',clinic:'Website + appointment booking',
 salon:'Website + online booking',spa:'Website + online booking',hotel:'Website + direct booking',education:'Website + enquiry funnel',school:'Website + enquiry funnel',college:'Website + enquiry funnel',realestate:'Website + property lead funnel'
}
function serviceFor(lead){const text=`${lead.category||''} ${lead.recommendedService||''}`.toLowerCase();return Object.entries(SERVICE_BY_CATEGORY).find(([k])=>text.includes(k))?.[1]||clean(lead.recommendedService)||'Modern business website + lead capture'}
export function buildProposal(lead={}){
 const name=clean(lead.name)||'Business';const service=serviceFor(lead);const score=Number(lead.score||0);const seo=Number(lead.seoScore||0);const noWebsite=!lead.website;
 const findings=[];if(noWebsite)findings.push('No dedicated website detected.');else if(seo<60)findings.push(`Current website SEO signals are ${seo}%.`);if(lead.mobileFriendlySignal===false)findings.push('Mobile viewport signal needs improvement.');if(lead.hasContactLink===false&&lead.website)findings.push('A clearer contact or booking path can improve enquiries.');if(!findings.length)findings.push('Existing web presence can be refined for stronger conversion and trust.');
 const deliverables=['Mobile-first responsive website','Clear service and business information','Contact / enquiry conversion path','Basic SEO and metadata setup','Performance and accessibility pass'];if(/ordering/i.test(service))deliverables.push('Online ordering or menu flow');if(/booking|appointment/i.test(service))deliverables.push('Booking / appointment enquiry flow');if(/property/i.test(service))deliverables.push('Property enquiry and lead capture flow');
 return {generatedAt:new Date().toISOString(),business:{name,category:clean(lead.category)||'Business',location:clean(lead.location),contactName:clean(lead.contactName),contactEmail:clean(lead.contactEmail||lead.email),contactPhone:clean(lead.contactPhone||lead.phone)},opportunity:{score,scoreLabel:clean(lead.scoreLabel)||'Opportunity',recommendedService:service,findings},proposal:{title:`Website Proposal — ${name}`,objective:`Create a professional online presence that makes it easier for ${name} customers to discover the business, understand its services, and take the next step.`,deliverables,process:['Discovery and content structure','Design and responsive implementation','Content, forms and conversion setup','SEO/performance checks','Launch handover'],timeline:'Typical small-business website: 5–10 working days after receiving required content and approvals.',investment:'Custom quote based on final scope',nextStep:'Review the scope, confirm the required pages/features, and schedule a short discovery call.'}}
}
